apiVersion: v1
name: traefik-crds
description: Traefik CRDs Helm chart for Kubernetes
version: 0.1.0
appVersion: "v27.0.2"
home: https://github.com/snowplow-devops/helm-charts
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
sources:
  - https://github.com/snowplow-devops/helm-charts
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: jamesarems
    url: https://github.com/jamesarems
    email: jamesarems@users.noreply.github.com
keywords:
  - traefik
  - crd
  - ingress
