{{- if and .Values.controller.enabled .Values.controller.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.controller.ingress.hostname | replace "." "-" }}
  labels:
    {{- include "snowplow.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestration
  annotations:
  {{- with .Values.controller.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.controller.ingress.enableTraefik | default true }}
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
  {{- end }}
spec:
  {{- if .Values.controller.ingress.enableTraefik | default true }}
  ingressClassName: traefik
  {{- end }}
  tls:
  - hosts:
      - {{ .Values.controller.ingress.hostname | quote }}
    secretName: {{ if .Values.controller.ingress.tlsSecretName }}{{ .Values.controller.ingress.tlsSecretName }}{{ else }}{{ .Values.controller.ingress.hostname | replace "." "-" }}-tls{{ end }}
  rules:
    - host: {{ .Values.controller.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.controller.ingress.path | default "/" }}
            pathType: {{ .Values.controller.ingress.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "avalanche.fullname" . }}-controller
                port:
                  number: {{ .Values.controller.service.port }}
{{- end }}
