{{- if .Values.logging.fluentbit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "avalanche.fullname" . }}-fluentbit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snowplow.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "avalanche.fullname" . }}-fluentbit
  labels:
    {{- include "snowplow.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "avalanche.fullname" . }}-fluentbit
  labels:
    {{- include "snowplow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "avalanche.fullname" . }}-fluentbit
subjects:
  - kind: ServiceAccount
    name: {{ include "avalanche.fullname" . }}-fluentbit
    namespace: {{ .Release.Namespace }}
{{- end }}
