apiVersion: v2
name: vertical-pod-autoscaler
description: A Helm Chart to deploy Vertical Pod Autoscaler components
version: 0.1.1
appVersion: 1.4.1
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
home: https://github.com/snowplow-devops/helm-charts
sources:
  - https://github.com/snowplow-devops/helm-charts
  - https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
maintainers:
  - name: ianarsenault
    url: https://github.com/ianarsenault
    email: ianarsenault@users.noreply.github.com
keywords:
  - vpa
  - vertical-pod-autoscaler
  - autoscaling
