{{- define "common.clusterrole" -}}
{{- $global := .Values.global -}}
{{- range .Values.services }}
{{- if and .clusterrole .clusterrole.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
{{- toYaml .clusterrole.rules  | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
