{{- define "common.ingress" -}}
{{- $global := .Values.global -}}
{{- $release := .Release -}}
{{- range $service := .Values.services }}
{{- if $service.service.ingress }}
{{- range $service.service.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ required "A valid hostname is required!" .hostname | replace "." "-" }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
  {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
  {{- end}}
  {{- if .enableTraefik | default true }}
    traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
  {{- end}}
  {{- if $service.service.ingressIPAllowlist }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $release.Namespace }}-{{ $service.name }}-ipallowlist@kubernetescrd
  {{- end }}
spec:
  {{- if .enableTraefik | default true }}
  ingressClassName: traefik
  {{- end}}
  tls:
  - hosts:
      - "{{ .hostname }}"
    secretName: {{ if .tlsSecretName }}{{ .tlsSecretName }}{{ else }}{{ .hostname | replace "." "-" }}-tls{{ end }}
  rules:
    - host: "{{ required "A valid hostname is required!" .hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ $service.name }}
                port:
                  number: {{ $service.service.port }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
