{{- define "common.pdb" -}}
{{- $global := .Values.global -}}
{{- range .Values.services }}
{{- if .podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .name }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not (kindIs "invalid" .podDisruptionBudget.minAvailable) }}
  minAvailable: {{ .podDisruptionBudget.minAvailable }}
  {{- else if not (kindIs "invalid" .podDisruptionBudget.maxUnavailable) }}
  maxUnavailable: {{ .podDisruptionBudget.maxUnavailable }}
  {{- else }}
  {{- fail (printf "PodDisruptionBudget for service '%s' must set either podDisruptionBudget.minAvailable or podDisruptionBudget.maxUnavailable" .name) }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
