{{- define "common.role" -}}
{{- $global := .Values.global -}}
{{- range .Values.services }}
{{- if and .cloudserviceaccount.deploy .customRole .customRole.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
{{- range $d := .customRole.definition }}
- apiGroups:
  {{- range $v := $d.apiGroups }}
  - {{ $v | quote }}
  {{- end }}
  resources:
  {{- range $v := $d.resources }}
  - {{ $v | quote }}
  {{- end }}
  verbs:
  {{- range $v := $d.verbs }}
  - {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
