{{- define "common.rolebinding" -}}
{{- $global := .Values.global -}}
{{- range .Values.services }}
{{- if and .cloudserviceaccount.deploy .customRole .customRole.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
  labels:
    {{- with $global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .cloudserviceaccount.name }}
roleRef:
  kind: Role
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
