apiVersion: v2
name: multi-service-deployment
description: A Helm Chart to deploy multiple services with a single release using the common library
version: 0.3.0
icon: https://raw.githubusercontent.com/snowplow-devops/helm-charts/master/docs/logo/snowplow.png
home: https://github.com/snowplow-devops/helm-charts
sources:
  - https://github.com/snowplow-devops/helm-charts
maintainers:
  - name: jparavisini
keywords:
  - service
  - deployment
  - multi-service
dependencies:
  - name: common
    version: 0.4.0
    repository: "https://snowplow-devops.github.io/helm-charts"
